#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
	xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1
fi

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          15
bspc config top_padding 45

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

bspc config focused_border_color "#ffd8d0"
bspc config normal_border_color "#584141"

# AutoStart Applications

feh --bg-fill $HOME/Pictures/kessoku-band-sakuraTree.png &
picom --config $HOME/.config/picom/picom.conf &
dunst -config $HOME/.config/dunst/dunstrc &
$HOME/.config/polybar/launch.sh &
